{{- if .Values.alertmanager.enabled -}}
apiVersion: v1
kind: Service
metadata:
{{- if .Values.alertmanager.headless.annotations }}
  annotations:
{{ toYaml .Values.alertmanager.headless.annotations | indent 4 }}
{{- end }}
  labels:
    app: {{ template "prometheus.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.alertmanager.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- if .Values.alertmanager.headless.labels }}
{{ toYaml .Values.alertmanager.headless.labels | indent 4 }}
{{- end }}
  name: {{ template "prometheus.alertmanager.fullname" . }}-headless
spec:
  clusterIP: None
  ports:
    - name: http
      port: {{ .Values.alertmanager.headless.servicePort }}
      protocol: TCP
      targetPort: 9093
{{- if .Values.alertmanager.headless.enableMeshPeer }}
    - name: meshpeer
      port: 6783
      protocol: TCP
      targetPort: 6783
{{- end }}
  selector:
    app: {{ template "prometheus.name" . }}
    component: "{{ .Values.alertmanager.name }}"
    release: {{ .Release.Name }}
{{- end }}
