apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ template "redis-ha.fullname" . }}-server-pdb
  labels:
{{ include "labels.standard" . | indent 4 }}
spec:
  selector:
    matchLabels:
      redis-node: "true"
      release: {{ .Release.Name }}
{{ toYaml .Values.podDisruptionBudget | indent 2 }}
